//! Safe FFI wrapper for [`libkrun`] — lightweight VM engine for
//! sandboxed code execution.
//!
//! This crate sits at L1 (platform primitives) and exposes:
//!
//! - [`sys`] — raw FFI bindings auto-generated by [`bindgen`]. Using
//!   this module is `unsafe` and only recommended for experimentation
//!   with new `libkrun` features ahead of the safe layer.
//! - `ctx` *(Unix only)* — type-safe 1:1 wrappers around every
//!   non-deprecated `krun_*` C entry point, with typed enums
//!   (`DiskFormat` / `SyncMode` / `LogStyle` / `KernelFormat` /
//!   `Feature`) and the crate [`Error`] type.
//!
//! Higher layers (e.g. `bux` or future `bux-vmm`) are expected to
//! build RAII handles and builder abstractions on top of `ctx`.
//!
//! # Build
//!
//! The build script (`build.rs`) automatically:
//! 1. Downloads the pre-built dynamic library from GitHub Releases
//!    (or uses a local path via `BUX_DEPS_DIR`).
//! 2. Configures the linker for dynamic linking.
//!
//! For local development, set `BUX_DEPS_DIR` to point at a directory
//! containing the pre-built `libkrun` dynamic library.
//!
//! [`libkrun`]: https://github.com/containers/libkrun
//! [`bindgen`]: https://docs.rs/bindgen

#![cfg_attr(docsrs, feature(doc_cfg))]

mod error;
pub mod sys;

#[cfg(unix)]
pub mod ctx;

#[cfg(unix)]
pub use ctx::{DiskFormat, Feature, KernelFormat, LogStyle, SyncMode};
pub use error::{Error, Result};
