/* automatically generated by rust-bindgen 0.72.1 */

pub const EXT2_ROOT_INO: u32 = 2;
pub const EXT2_GOOD_OLD_FIRST_INO: u32 = 11;
pub const EXT2_GOOD_OLD_REV: u32 = 0;
pub const EXT2_DYNAMIC_REV: u32 = 1;
pub const EXT2_GOOD_OLD_INODE_SIZE: u32 = 128;
pub const EXT2_FT_UNKNOWN: u32 = 0;
pub const EXT2_FT_REG_FILE: u32 = 1;
pub const EXT2_FT_DIR: u32 = 2;
pub const EXT2_FT_CHRDEV: u32 = 3;
pub const EXT2_FT_BLKDEV: u32 = 4;
pub const EXT2_FT_FIFO: u32 = 5;
pub const EXT2_FT_SOCK: u32 = 6;
pub const EXT2_FT_SYMLINK: u32 = 7;
pub const EXT2_FT_MAX: u32 = 8;
pub const EXT2_FLAG_RW: u32 = 1;
pub const EXT2_FLAG_CHANGED: u32 = 2;
pub const EXT2_FLAG_DIRTY: u32 = 4;
pub const EXT2_FLAG_VALID: u32 = 8;
pub const EXT2_FLAG_IB_DIRTY: u32 = 16;
pub const EXT2_FLAG_BB_DIRTY: u32 = 32;
pub const EXT2_FLAG_SWAP_BYTES: u32 = 64;
pub const EXT2_FLAG_SWAP_BYTES_READ: u32 = 128;
pub const EXT2_FLAG_SWAP_BYTES_WRITE: u32 = 256;
pub const EXT2_FLAG_MASTER_SB_ONLY: u32 = 512;
pub const EXT2_FLAG_FORCE: u32 = 1024;
pub const EXT2_FLAG_SUPER_ONLY: u32 = 2048;
pub const EXT2_FLAG_JOURNAL_DEV_OK: u32 = 4096;
pub const EXT2_FLAG_IMAGE_FILE: u32 = 8192;
pub const EXT2_FLAG_EXCLUSIVE: u32 = 16384;
pub const EXT2_FLAG_SOFTSUPP_FEATURES: u32 = 32768;
pub const EXT2_FLAG_NOFREE_ON_ERROR: u32 = 65536;
pub const EXT2_FLAG_64BITS: u32 = 131072;
pub const EXT2_FLAG_PRINT_PROGRESS: u32 = 262144;
pub const EXT2_FLAG_DIRECT_IO: u32 = 524288;
pub const EXT2_FLAG_SKIP_MMP: u32 = 1048576;
pub const EXT2_FLAG_IGNORE_CSUM_ERRORS: u32 = 2097152;
pub const EXT2_FLAG_SHARE_DUP: u32 = 4194304;
pub const EXT2_FLAG_IGNORE_SB_ERRORS: u32 = 8388608;
pub const EXT2_FLAG_BBITMAP_TAIL_PROBLEM: u32 = 16777216;
pub const EXT2_FLAG_IBITMAP_TAIL_PROBLEM: u32 = 33554432;
pub const EXT2_FLAG_THREADS: u32 = 67108864;
pub const EXT2_FLAG_IGNORE_SWAP_DIRENT: u32 = 134217728;
pub const LINUX_S_IFMT: u32 = 61440;
pub const LINUX_S_IFSOCK: u32 = 49152;
pub const LINUX_S_IFLNK: u32 = 40960;
pub const LINUX_S_IFREG: u32 = 32768;
pub const LINUX_S_IFBLK: u32 = 24576;
pub const LINUX_S_IFDIR: u32 = 16384;
pub const LINUX_S_IFCHR: u32 = 8192;
pub const LINUX_S_IFIFO: u32 = 4096;
pub const EXT2_FLAG_FLUSH_NO_SYNC: u32 = 1;
pub type __dev_t = ::core::ffi::c_ulong;
pub type __uid_t = ::core::ffi::c_uint;
pub type __gid_t = ::core::ffi::c_uint;
pub type __ino_t = ::core::ffi::c_ulong;
pub type __mode_t = ::core::ffi::c_uint;
pub type __nlink_t = ::core::ffi::c_ulong;
pub type __off_t = ::core::ffi::c_long;
pub type __time_t = ::core::ffi::c_long;
pub type __blksize_t = ::core::ffi::c_long;
pub type __blkcnt_t = ::core::ffi::c_long;
pub type __syscall_slong_t = ::core::ffi::c_long;
pub type ino_t = __ino_t;
pub type dev_t = __dev_t;
pub type mode_t = __mode_t;
pub type time_t = __time_t;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct timespec {
    pub tv_sec: __time_t,
    pub tv_nsec: __syscall_slong_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of timespec"][::core::mem::size_of::<timespec>() - 16usize];
    ["Alignment of timespec"][::core::mem::align_of::<timespec>() - 8usize];
    ["Offset of field: timespec::tv_sec"][::core::mem::offset_of!(timespec, tv_sec) - 0usize];
    ["Offset of field: timespec::tv_nsec"][::core::mem::offset_of!(timespec, tv_nsec) - 8usize];
};
pub type __u8 = ::core::ffi::c_uchar;
pub type __u16 = ::core::ffi::c_ushort;
pub type __s16 = ::core::ffi::c_short;
pub type __u32 = ::core::ffi::c_uint;
pub type __u64 = ::core::ffi::c_ulonglong;
pub type __le16 = __u16;
pub type __le32 = __u32;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ext2_inode {
    pub i_mode: __u16,
    pub i_uid: __u16,
    pub i_size: __u32,
    pub i_atime: __u32,
    pub i_ctime: __u32,
    pub i_mtime: __u32,
    pub i_dtime: __u32,
    pub i_gid: __u16,
    pub i_links_count: __u16,
    pub i_blocks: __u32,
    pub i_flags: __u32,
    pub osd1: ext2_inode__bindgen_ty_1,
    pub i_block: [__u32; 15usize],
    pub i_generation: __u32,
    pub i_file_acl: __u32,
    pub i_size_high: __u32,
    pub i_faddr: __u32,
    pub osd2: ext2_inode__bindgen_ty_2,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union ext2_inode__bindgen_ty_1 {
    pub linux1: ext2_inode__bindgen_ty_1__bindgen_ty_1,
    pub hurd1: ext2_inode__bindgen_ty_1__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct ext2_inode__bindgen_ty_1__bindgen_ty_1 {
    pub l_i_version: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2_inode__bindgen_ty_1__bindgen_ty_1"]
        [::core::mem::size_of::<ext2_inode__bindgen_ty_1__bindgen_ty_1>() - 4usize];
    ["Alignment of ext2_inode__bindgen_ty_1__bindgen_ty_1"]
        [::core::mem::align_of::<ext2_inode__bindgen_ty_1__bindgen_ty_1>() - 4usize];
    ["Offset of field: ext2_inode__bindgen_ty_1__bindgen_ty_1::l_i_version"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_1__bindgen_ty_1, l_i_version) - 0usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct ext2_inode__bindgen_ty_1__bindgen_ty_2 {
    pub h_i_translator: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2_inode__bindgen_ty_1__bindgen_ty_2"]
        [::core::mem::size_of::<ext2_inode__bindgen_ty_1__bindgen_ty_2>() - 4usize];
    ["Alignment of ext2_inode__bindgen_ty_1__bindgen_ty_2"]
        [::core::mem::align_of::<ext2_inode__bindgen_ty_1__bindgen_ty_2>() - 4usize];
    ["Offset of field: ext2_inode__bindgen_ty_1__bindgen_ty_2::h_i_translator"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_1__bindgen_ty_2, h_i_translator) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2_inode__bindgen_ty_1"]
        [::core::mem::size_of::<ext2_inode__bindgen_ty_1>() - 4usize];
    ["Alignment of ext2_inode__bindgen_ty_1"]
        [::core::mem::align_of::<ext2_inode__bindgen_ty_1>() - 4usize];
    ["Offset of field: ext2_inode__bindgen_ty_1::linux1"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_1, linux1) - 0usize];
    ["Offset of field: ext2_inode__bindgen_ty_1::hurd1"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_1, hurd1) - 0usize];
};
impl Default for ext2_inode__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union ext2_inode__bindgen_ty_2 {
    pub linux2: ext2_inode__bindgen_ty_2__bindgen_ty_1,
    pub hurd2: ext2_inode__bindgen_ty_2__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct ext2_inode__bindgen_ty_2__bindgen_ty_1 {
    pub l_i_blocks_hi: __u16,
    pub l_i_file_acl_high: __u16,
    pub l_i_uid_high: __u16,
    pub l_i_gid_high: __u16,
    pub l_i_checksum_lo: __u16,
    pub l_i_reserved: __u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2_inode__bindgen_ty_2__bindgen_ty_1"]
        [::core::mem::size_of::<ext2_inode__bindgen_ty_2__bindgen_ty_1>() - 12usize];
    ["Alignment of ext2_inode__bindgen_ty_2__bindgen_ty_1"]
        [::core::mem::align_of::<ext2_inode__bindgen_ty_2__bindgen_ty_1>() - 2usize];
    ["Offset of field: ext2_inode__bindgen_ty_2__bindgen_ty_1::l_i_blocks_hi"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_2__bindgen_ty_1, l_i_blocks_hi) - 0usize];
    ["Offset of field: ext2_inode__bindgen_ty_2__bindgen_ty_1::l_i_file_acl_high"][::core::mem::offset_of!(
        ext2_inode__bindgen_ty_2__bindgen_ty_1,
        l_i_file_acl_high
    ) - 2usize];
    ["Offset of field: ext2_inode__bindgen_ty_2__bindgen_ty_1::l_i_uid_high"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_2__bindgen_ty_1, l_i_uid_high) - 4usize];
    ["Offset of field: ext2_inode__bindgen_ty_2__bindgen_ty_1::l_i_gid_high"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_2__bindgen_ty_1, l_i_gid_high) - 6usize];
    ["Offset of field: ext2_inode__bindgen_ty_2__bindgen_ty_1::l_i_checksum_lo"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_2__bindgen_ty_1, l_i_checksum_lo) - 8usize];
    ["Offset of field: ext2_inode__bindgen_ty_2__bindgen_ty_1::l_i_reserved"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_2__bindgen_ty_1, l_i_reserved) - 10usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct ext2_inode__bindgen_ty_2__bindgen_ty_2 {
    pub h_i_frag: __u8,
    pub h_i_fsize: __u8,
    pub h_i_mode_high: __u16,
    pub h_i_uid_high: __u16,
    pub h_i_gid_high: __u16,
    pub h_i_author: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2_inode__bindgen_ty_2__bindgen_ty_2"]
        [::core::mem::size_of::<ext2_inode__bindgen_ty_2__bindgen_ty_2>() - 12usize];
    ["Alignment of ext2_inode__bindgen_ty_2__bindgen_ty_2"]
        [::core::mem::align_of::<ext2_inode__bindgen_ty_2__bindgen_ty_2>() - 4usize];
    ["Offset of field: ext2_inode__bindgen_ty_2__bindgen_ty_2::h_i_frag"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_2__bindgen_ty_2, h_i_frag) - 0usize];
    ["Offset of field: ext2_inode__bindgen_ty_2__bindgen_ty_2::h_i_fsize"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_2__bindgen_ty_2, h_i_fsize) - 1usize];
    ["Offset of field: ext2_inode__bindgen_ty_2__bindgen_ty_2::h_i_mode_high"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_2__bindgen_ty_2, h_i_mode_high) - 2usize];
    ["Offset of field: ext2_inode__bindgen_ty_2__bindgen_ty_2::h_i_uid_high"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_2__bindgen_ty_2, h_i_uid_high) - 4usize];
    ["Offset of field: ext2_inode__bindgen_ty_2__bindgen_ty_2::h_i_gid_high"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_2__bindgen_ty_2, h_i_gid_high) - 6usize];
    ["Offset of field: ext2_inode__bindgen_ty_2__bindgen_ty_2::h_i_author"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_2__bindgen_ty_2, h_i_author) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2_inode__bindgen_ty_2"]
        [::core::mem::size_of::<ext2_inode__bindgen_ty_2>() - 12usize];
    ["Alignment of ext2_inode__bindgen_ty_2"]
        [::core::mem::align_of::<ext2_inode__bindgen_ty_2>() - 4usize];
    ["Offset of field: ext2_inode__bindgen_ty_2::linux2"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_2, linux2) - 0usize];
    ["Offset of field: ext2_inode__bindgen_ty_2::hurd2"]
        [::core::mem::offset_of!(ext2_inode__bindgen_ty_2, hurd2) - 0usize];
};
impl Default for ext2_inode__bindgen_ty_2 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2_inode"][::core::mem::size_of::<ext2_inode>() - 128usize];
    ["Alignment of ext2_inode"][::core::mem::align_of::<ext2_inode>() - 4usize];
    ["Offset of field: ext2_inode::i_mode"][::core::mem::offset_of!(ext2_inode, i_mode) - 0usize];
    ["Offset of field: ext2_inode::i_uid"][::core::mem::offset_of!(ext2_inode, i_uid) - 2usize];
    ["Offset of field: ext2_inode::i_size"][::core::mem::offset_of!(ext2_inode, i_size) - 4usize];
    ["Offset of field: ext2_inode::i_atime"][::core::mem::offset_of!(ext2_inode, i_atime) - 8usize];
    ["Offset of field: ext2_inode::i_ctime"]
        [::core::mem::offset_of!(ext2_inode, i_ctime) - 12usize];
    ["Offset of field: ext2_inode::i_mtime"]
        [::core::mem::offset_of!(ext2_inode, i_mtime) - 16usize];
    ["Offset of field: ext2_inode::i_dtime"]
        [::core::mem::offset_of!(ext2_inode, i_dtime) - 20usize];
    ["Offset of field: ext2_inode::i_gid"][::core::mem::offset_of!(ext2_inode, i_gid) - 24usize];
    ["Offset of field: ext2_inode::i_links_count"]
        [::core::mem::offset_of!(ext2_inode, i_links_count) - 26usize];
    ["Offset of field: ext2_inode::i_blocks"]
        [::core::mem::offset_of!(ext2_inode, i_blocks) - 28usize];
    ["Offset of field: ext2_inode::i_flags"]
        [::core::mem::offset_of!(ext2_inode, i_flags) - 32usize];
    ["Offset of field: ext2_inode::osd1"][::core::mem::offset_of!(ext2_inode, osd1) - 36usize];
    ["Offset of field: ext2_inode::i_block"]
        [::core::mem::offset_of!(ext2_inode, i_block) - 40usize];
    ["Offset of field: ext2_inode::i_generation"]
        [::core::mem::offset_of!(ext2_inode, i_generation) - 100usize];
    ["Offset of field: ext2_inode::i_file_acl"]
        [::core::mem::offset_of!(ext2_inode, i_file_acl) - 104usize];
    ["Offset of field: ext2_inode::i_size_high"]
        [::core::mem::offset_of!(ext2_inode, i_size_high) - 108usize];
    ["Offset of field: ext2_inode::i_faddr"]
        [::core::mem::offset_of!(ext2_inode, i_faddr) - 112usize];
    ["Offset of field: ext2_inode::osd2"][::core::mem::offset_of!(ext2_inode, osd2) - 116usize];
};
impl Default for ext2_inode {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ext2_inode_large {
    pub i_mode: __u16,
    pub i_uid: __u16,
    pub i_size: __u32,
    pub i_atime: __u32,
    pub i_ctime: __u32,
    pub i_mtime: __u32,
    pub i_dtime: __u32,
    pub i_gid: __u16,
    pub i_links_count: __u16,
    pub i_blocks: __u32,
    pub i_flags: __u32,
    pub osd1: ext2_inode_large__bindgen_ty_1,
    pub i_block: [__u32; 15usize],
    pub i_generation: __u32,
    pub i_file_acl: __u32,
    pub i_size_high: __u32,
    pub i_faddr: __u32,
    pub osd2: ext2_inode_large__bindgen_ty_2,
    pub i_extra_isize: __u16,
    pub i_checksum_hi: __u16,
    pub i_ctime_extra: __u32,
    pub i_mtime_extra: __u32,
    pub i_atime_extra: __u32,
    pub i_crtime: __u32,
    pub i_crtime_extra: __u32,
    pub i_version_hi: __u32,
    pub i_projid: __u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union ext2_inode_large__bindgen_ty_1 {
    pub linux1: ext2_inode_large__bindgen_ty_1__bindgen_ty_1,
    pub hurd1: ext2_inode_large__bindgen_ty_1__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct ext2_inode_large__bindgen_ty_1__bindgen_ty_1 {
    pub l_i_version: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2_inode_large__bindgen_ty_1__bindgen_ty_1"]
        [::core::mem::size_of::<ext2_inode_large__bindgen_ty_1__bindgen_ty_1>() - 4usize];
    ["Alignment of ext2_inode_large__bindgen_ty_1__bindgen_ty_1"]
        [::core::mem::align_of::<ext2_inode_large__bindgen_ty_1__bindgen_ty_1>() - 4usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_1__bindgen_ty_1::l_i_version"][::core::mem::offset_of!(
        ext2_inode_large__bindgen_ty_1__bindgen_ty_1,
        l_i_version
    ) - 0usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct ext2_inode_large__bindgen_ty_1__bindgen_ty_2 {
    pub h_i_translator: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2_inode_large__bindgen_ty_1__bindgen_ty_2"]
        [::core::mem::size_of::<ext2_inode_large__bindgen_ty_1__bindgen_ty_2>() - 4usize];
    ["Alignment of ext2_inode_large__bindgen_ty_1__bindgen_ty_2"]
        [::core::mem::align_of::<ext2_inode_large__bindgen_ty_1__bindgen_ty_2>() - 4usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_1__bindgen_ty_2::h_i_translator"][::core::mem::offset_of!(
        ext2_inode_large__bindgen_ty_1__bindgen_ty_2,
        h_i_translator
    ) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2_inode_large__bindgen_ty_1"]
        [::core::mem::size_of::<ext2_inode_large__bindgen_ty_1>() - 4usize];
    ["Alignment of ext2_inode_large__bindgen_ty_1"]
        [::core::mem::align_of::<ext2_inode_large__bindgen_ty_1>() - 4usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_1::linux1"]
        [::core::mem::offset_of!(ext2_inode_large__bindgen_ty_1, linux1) - 0usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_1::hurd1"]
        [::core::mem::offset_of!(ext2_inode_large__bindgen_ty_1, hurd1) - 0usize];
};
impl Default for ext2_inode_large__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union ext2_inode_large__bindgen_ty_2 {
    pub linux2: ext2_inode_large__bindgen_ty_2__bindgen_ty_1,
    pub hurd2: ext2_inode_large__bindgen_ty_2__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct ext2_inode_large__bindgen_ty_2__bindgen_ty_1 {
    pub l_i_blocks_hi: __u16,
    pub l_i_file_acl_high: __u16,
    pub l_i_uid_high: __u16,
    pub l_i_gid_high: __u16,
    pub l_i_checksum_lo: __u16,
    pub l_i_reserved: __u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2_inode_large__bindgen_ty_2__bindgen_ty_1"]
        [::core::mem::size_of::<ext2_inode_large__bindgen_ty_2__bindgen_ty_1>() - 12usize];
    ["Alignment of ext2_inode_large__bindgen_ty_2__bindgen_ty_1"]
        [::core::mem::align_of::<ext2_inode_large__bindgen_ty_2__bindgen_ty_1>() - 2usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_2__bindgen_ty_1::l_i_blocks_hi"][::core::mem::offset_of!(
        ext2_inode_large__bindgen_ty_2__bindgen_ty_1,
        l_i_blocks_hi
    ) - 0usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_2__bindgen_ty_1::l_i_file_acl_high"][::core::mem::offset_of!(
        ext2_inode_large__bindgen_ty_2__bindgen_ty_1,
        l_i_file_acl_high
    )
        - 2usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_2__bindgen_ty_1::l_i_uid_high"][::core::mem::offset_of!(
        ext2_inode_large__bindgen_ty_2__bindgen_ty_1,
        l_i_uid_high
    ) - 4usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_2__bindgen_ty_1::l_i_gid_high"][::core::mem::offset_of!(
        ext2_inode_large__bindgen_ty_2__bindgen_ty_1,
        l_i_gid_high
    ) - 6usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_2__bindgen_ty_1::l_i_checksum_lo"][::core::mem::offset_of!(
        ext2_inode_large__bindgen_ty_2__bindgen_ty_1,
        l_i_checksum_lo
    ) - 8usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_2__bindgen_ty_1::l_i_reserved"][::core::mem::offset_of!(
        ext2_inode_large__bindgen_ty_2__bindgen_ty_1,
        l_i_reserved
    ) - 10usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct ext2_inode_large__bindgen_ty_2__bindgen_ty_2 {
    pub h_i_frag: __u8,
    pub h_i_fsize: __u8,
    pub h_i_mode_high: __u16,
    pub h_i_uid_high: __u16,
    pub h_i_gid_high: __u16,
    pub h_i_author: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2_inode_large__bindgen_ty_2__bindgen_ty_2"]
        [::core::mem::size_of::<ext2_inode_large__bindgen_ty_2__bindgen_ty_2>() - 12usize];
    ["Alignment of ext2_inode_large__bindgen_ty_2__bindgen_ty_2"]
        [::core::mem::align_of::<ext2_inode_large__bindgen_ty_2__bindgen_ty_2>() - 4usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_2__bindgen_ty_2::h_i_frag"]
        [::core::mem::offset_of!(ext2_inode_large__bindgen_ty_2__bindgen_ty_2, h_i_frag) - 0usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_2__bindgen_ty_2::h_i_fsize"]
        [::core::mem::offset_of!(ext2_inode_large__bindgen_ty_2__bindgen_ty_2, h_i_fsize) - 1usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_2__bindgen_ty_2::h_i_mode_high"][::core::mem::offset_of!(
        ext2_inode_large__bindgen_ty_2__bindgen_ty_2,
        h_i_mode_high
    ) - 2usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_2__bindgen_ty_2::h_i_uid_high"][::core::mem::offset_of!(
        ext2_inode_large__bindgen_ty_2__bindgen_ty_2,
        h_i_uid_high
    ) - 4usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_2__bindgen_ty_2::h_i_gid_high"][::core::mem::offset_of!(
        ext2_inode_large__bindgen_ty_2__bindgen_ty_2,
        h_i_gid_high
    ) - 6usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_2__bindgen_ty_2::h_i_author"][::core::mem::offset_of!(
        ext2_inode_large__bindgen_ty_2__bindgen_ty_2,
        h_i_author
    ) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2_inode_large__bindgen_ty_2"]
        [::core::mem::size_of::<ext2_inode_large__bindgen_ty_2>() - 12usize];
    ["Alignment of ext2_inode_large__bindgen_ty_2"]
        [::core::mem::align_of::<ext2_inode_large__bindgen_ty_2>() - 4usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_2::linux2"]
        [::core::mem::offset_of!(ext2_inode_large__bindgen_ty_2, linux2) - 0usize];
    ["Offset of field: ext2_inode_large__bindgen_ty_2::hurd2"]
        [::core::mem::offset_of!(ext2_inode_large__bindgen_ty_2, hurd2) - 0usize];
};
impl Default for ext2_inode_large__bindgen_ty_2 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2_inode_large"][::core::mem::size_of::<ext2_inode_large>() - 160usize];
    ["Alignment of ext2_inode_large"][::core::mem::align_of::<ext2_inode_large>() - 4usize];
    ["Offset of field: ext2_inode_large::i_mode"]
        [::core::mem::offset_of!(ext2_inode_large, i_mode) - 0usize];
    ["Offset of field: ext2_inode_large::i_uid"]
        [::core::mem::offset_of!(ext2_inode_large, i_uid) - 2usize];
    ["Offset of field: ext2_inode_large::i_size"]
        [::core::mem::offset_of!(ext2_inode_large, i_size) - 4usize];
    ["Offset of field: ext2_inode_large::i_atime"]
        [::core::mem::offset_of!(ext2_inode_large, i_atime) - 8usize];
    ["Offset of field: ext2_inode_large::i_ctime"]
        [::core::mem::offset_of!(ext2_inode_large, i_ctime) - 12usize];
    ["Offset of field: ext2_inode_large::i_mtime"]
        [::core::mem::offset_of!(ext2_inode_large, i_mtime) - 16usize];
    ["Offset of field: ext2_inode_large::i_dtime"]
        [::core::mem::offset_of!(ext2_inode_large, i_dtime) - 20usize];
    ["Offset of field: ext2_inode_large::i_gid"]
        [::core::mem::offset_of!(ext2_inode_large, i_gid) - 24usize];
    ["Offset of field: ext2_inode_large::i_links_count"]
        [::core::mem::offset_of!(ext2_inode_large, i_links_count) - 26usize];
    ["Offset of field: ext2_inode_large::i_blocks"]
        [::core::mem::offset_of!(ext2_inode_large, i_blocks) - 28usize];
    ["Offset of field: ext2_inode_large::i_flags"]
        [::core::mem::offset_of!(ext2_inode_large, i_flags) - 32usize];
    ["Offset of field: ext2_inode_large::osd1"]
        [::core::mem::offset_of!(ext2_inode_large, osd1) - 36usize];
    ["Offset of field: ext2_inode_large::i_block"]
        [::core::mem::offset_of!(ext2_inode_large, i_block) - 40usize];
    ["Offset of field: ext2_inode_large::i_generation"]
        [::core::mem::offset_of!(ext2_inode_large, i_generation) - 100usize];
    ["Offset of field: ext2_inode_large::i_file_acl"]
        [::core::mem::offset_of!(ext2_inode_large, i_file_acl) - 104usize];
    ["Offset of field: ext2_inode_large::i_size_high"]
        [::core::mem::offset_of!(ext2_inode_large, i_size_high) - 108usize];
    ["Offset of field: ext2_inode_large::i_faddr"]
        [::core::mem::offset_of!(ext2_inode_large, i_faddr) - 112usize];
    ["Offset of field: ext2_inode_large::osd2"]
        [::core::mem::offset_of!(ext2_inode_large, osd2) - 116usize];
    ["Offset of field: ext2_inode_large::i_extra_isize"]
        [::core::mem::offset_of!(ext2_inode_large, i_extra_isize) - 128usize];
    ["Offset of field: ext2_inode_large::i_checksum_hi"]
        [::core::mem::offset_of!(ext2_inode_large, i_checksum_hi) - 130usize];
    ["Offset of field: ext2_inode_large::i_ctime_extra"]
        [::core::mem::offset_of!(ext2_inode_large, i_ctime_extra) - 132usize];
    ["Offset of field: ext2_inode_large::i_mtime_extra"]
        [::core::mem::offset_of!(ext2_inode_large, i_mtime_extra) - 136usize];
    ["Offset of field: ext2_inode_large::i_atime_extra"]
        [::core::mem::offset_of!(ext2_inode_large, i_atime_extra) - 140usize];
    ["Offset of field: ext2_inode_large::i_crtime"]
        [::core::mem::offset_of!(ext2_inode_large, i_crtime) - 144usize];
    ["Offset of field: ext2_inode_large::i_crtime_extra"]
        [::core::mem::offset_of!(ext2_inode_large, i_crtime_extra) - 148usize];
    ["Offset of field: ext2_inode_large::i_version_hi"]
        [::core::mem::offset_of!(ext2_inode_large, i_version_hi) - 152usize];
    ["Offset of field: ext2_inode_large::i_projid"]
        [::core::mem::offset_of!(ext2_inode_large, i_projid) - 156usize];
};
impl Default for ext2_inode_large {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct ext2_super_block {
    pub s_inodes_count: __u32,
    pub s_blocks_count: __u32,
    pub s_r_blocks_count: __u32,
    pub s_free_blocks_count: __u32,
    pub s_free_inodes_count: __u32,
    pub s_first_data_block: __u32,
    pub s_log_block_size: __u32,
    pub s_log_cluster_size: __u32,
    pub s_blocks_per_group: __u32,
    pub s_clusters_per_group: __u32,
    pub s_inodes_per_group: __u32,
    pub s_mtime: __u32,
    pub s_wtime: __u32,
    pub s_mnt_count: __u16,
    pub s_max_mnt_count: __s16,
    pub s_magic: __u16,
    pub s_state: __u16,
    pub s_errors: __u16,
    pub s_minor_rev_level: __u16,
    pub s_lastcheck: __u32,
    pub s_checkinterval: __u32,
    pub s_creator_os: __u32,
    pub s_rev_level: __u32,
    pub s_def_resuid: __u16,
    pub s_def_resgid: __u16,
    pub s_first_ino: __u32,
    pub s_inode_size: __u16,
    pub s_block_group_nr: __u16,
    pub s_feature_compat: __u32,
    pub s_feature_incompat: __u32,
    pub s_feature_ro_compat: __u32,
    pub s_uuid: [__u8; 16usize],
    pub s_volume_name: [__u8; 16usize],
    pub s_last_mounted: [__u8; 64usize],
    pub s_algorithm_usage_bitmap: __u32,
    pub s_prealloc_blocks: __u8,
    pub s_prealloc_dir_blocks: __u8,
    pub s_reserved_gdt_blocks: __u16,
    pub s_journal_uuid: [__u8; 16usize],
    pub s_journal_inum: __u32,
    pub s_journal_dev: __u32,
    pub s_last_orphan: __u32,
    pub s_hash_seed: [__u32; 4usize],
    pub s_def_hash_version: __u8,
    pub s_jnl_backup_type: __u8,
    pub s_desc_size: __u16,
    pub s_default_mount_opts: __u32,
    pub s_first_meta_bg: __u32,
    pub s_mkfs_time: __u32,
    pub s_jnl_blocks: [__u32; 17usize],
    pub s_blocks_count_hi: __u32,
    pub s_r_blocks_count_hi: __u32,
    pub s_free_blocks_hi: __u32,
    pub s_min_extra_isize: __u16,
    pub s_want_extra_isize: __u16,
    pub s_flags: __u32,
    pub s_raid_stride: __u16,
    pub s_mmp_update_interval: __u16,
    pub s_mmp_block: __u64,
    pub s_raid_stripe_width: __u32,
    pub s_log_groups_per_flex: __u8,
    pub s_checksum_type: __u8,
    pub s_encryption_level: __u8,
    pub s_reserved_pad: __u8,
    pub s_kbytes_written: __u64,
    pub s_snapshot_inum: __u32,
    pub s_snapshot_id: __u32,
    pub s_snapshot_r_blocks_count: __u64,
    pub s_snapshot_list: __u32,
    pub s_error_count: __u32,
    pub s_first_error_time: __u32,
    pub s_first_error_ino: __u32,
    pub s_first_error_block: __u64,
    pub s_first_error_func: [__u8; 32usize],
    pub s_first_error_line: __u32,
    pub s_last_error_time: __u32,
    pub s_last_error_ino: __u32,
    pub s_last_error_line: __u32,
    pub s_last_error_block: __u64,
    pub s_last_error_func: [__u8; 32usize],
    pub s_mount_opts: [__u8; 64usize],
    pub s_usr_quota_inum: __u32,
    pub s_grp_quota_inum: __u32,
    pub s_overhead_clusters: __u32,
    pub s_backup_bgs: [__u32; 2usize],
    pub s_encrypt_algos: [__u8; 4usize],
    pub s_encrypt_pw_salt: [__u8; 16usize],
    pub s_lpf_ino: __le32,
    pub s_prj_quota_inum: __le32,
    pub s_checksum_seed: __le32,
    pub s_wtime_hi: __u8,
    pub s_mtime_hi: __u8,
    pub s_mkfs_time_hi: __u8,
    pub s_lastcheck_hi: __u8,
    pub s_first_error_time_hi: __u8,
    pub s_last_error_time_hi: __u8,
    pub s_first_error_errcode: __u8,
    pub s_last_error_errcode: __u8,
    pub s_encoding: __le16,
    pub s_encoding_flags: __le16,
    pub s_orphan_file_inum: __le32,
    pub s_reserved: [__le32; 94usize],
    pub s_checksum: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2_super_block"][::core::mem::size_of::<ext2_super_block>() - 1024usize];
    ["Alignment of ext2_super_block"][::core::mem::align_of::<ext2_super_block>() - 8usize];
    ["Offset of field: ext2_super_block::s_inodes_count"]
        [::core::mem::offset_of!(ext2_super_block, s_inodes_count) - 0usize];
    ["Offset of field: ext2_super_block::s_blocks_count"]
        [::core::mem::offset_of!(ext2_super_block, s_blocks_count) - 4usize];
    ["Offset of field: ext2_super_block::s_r_blocks_count"]
        [::core::mem::offset_of!(ext2_super_block, s_r_blocks_count) - 8usize];
    ["Offset of field: ext2_super_block::s_free_blocks_count"]
        [::core::mem::offset_of!(ext2_super_block, s_free_blocks_count) - 12usize];
    ["Offset of field: ext2_super_block::s_free_inodes_count"]
        [::core::mem::offset_of!(ext2_super_block, s_free_inodes_count) - 16usize];
    ["Offset of field: ext2_super_block::s_first_data_block"]
        [::core::mem::offset_of!(ext2_super_block, s_first_data_block) - 20usize];
    ["Offset of field: ext2_super_block::s_log_block_size"]
        [::core::mem::offset_of!(ext2_super_block, s_log_block_size) - 24usize];
    ["Offset of field: ext2_super_block::s_log_cluster_size"]
        [::core::mem::offset_of!(ext2_super_block, s_log_cluster_size) - 28usize];
    ["Offset of field: ext2_super_block::s_blocks_per_group"]
        [::core::mem::offset_of!(ext2_super_block, s_blocks_per_group) - 32usize];
    ["Offset of field: ext2_super_block::s_clusters_per_group"]
        [::core::mem::offset_of!(ext2_super_block, s_clusters_per_group) - 36usize];
    ["Offset of field: ext2_super_block::s_inodes_per_group"]
        [::core::mem::offset_of!(ext2_super_block, s_inodes_per_group) - 40usize];
    ["Offset of field: ext2_super_block::s_mtime"]
        [::core::mem::offset_of!(ext2_super_block, s_mtime) - 44usize];
    ["Offset of field: ext2_super_block::s_wtime"]
        [::core::mem::offset_of!(ext2_super_block, s_wtime) - 48usize];
    ["Offset of field: ext2_super_block::s_mnt_count"]
        [::core::mem::offset_of!(ext2_super_block, s_mnt_count) - 52usize];
    ["Offset of field: ext2_super_block::s_max_mnt_count"]
        [::core::mem::offset_of!(ext2_super_block, s_max_mnt_count) - 54usize];
    ["Offset of field: ext2_super_block::s_magic"]
        [::core::mem::offset_of!(ext2_super_block, s_magic) - 56usize];
    ["Offset of field: ext2_super_block::s_state"]
        [::core::mem::offset_of!(ext2_super_block, s_state) - 58usize];
    ["Offset of field: ext2_super_block::s_errors"]
        [::core::mem::offset_of!(ext2_super_block, s_errors) - 60usize];
    ["Offset of field: ext2_super_block::s_minor_rev_level"]
        [::core::mem::offset_of!(ext2_super_block, s_minor_rev_level) - 62usize];
    ["Offset of field: ext2_super_block::s_lastcheck"]
        [::core::mem::offset_of!(ext2_super_block, s_lastcheck) - 64usize];
    ["Offset of field: ext2_super_block::s_checkinterval"]
        [::core::mem::offset_of!(ext2_super_block, s_checkinterval) - 68usize];
    ["Offset of field: ext2_super_block::s_creator_os"]
        [::core::mem::offset_of!(ext2_super_block, s_creator_os) - 72usize];
    ["Offset of field: ext2_super_block::s_rev_level"]
        [::core::mem::offset_of!(ext2_super_block, s_rev_level) - 76usize];
    ["Offset of field: ext2_super_block::s_def_resuid"]
        [::core::mem::offset_of!(ext2_super_block, s_def_resuid) - 80usize];
    ["Offset of field: ext2_super_block::s_def_resgid"]
        [::core::mem::offset_of!(ext2_super_block, s_def_resgid) - 82usize];
    ["Offset of field: ext2_super_block::s_first_ino"]
        [::core::mem::offset_of!(ext2_super_block, s_first_ino) - 84usize];
    ["Offset of field: ext2_super_block::s_inode_size"]
        [::core::mem::offset_of!(ext2_super_block, s_inode_size) - 88usize];
    ["Offset of field: ext2_super_block::s_block_group_nr"]
        [::core::mem::offset_of!(ext2_super_block, s_block_group_nr) - 90usize];
    ["Offset of field: ext2_super_block::s_feature_compat"]
        [::core::mem::offset_of!(ext2_super_block, s_feature_compat) - 92usize];
    ["Offset of field: ext2_super_block::s_feature_incompat"]
        [::core::mem::offset_of!(ext2_super_block, s_feature_incompat) - 96usize];
    ["Offset of field: ext2_super_block::s_feature_ro_compat"]
        [::core::mem::offset_of!(ext2_super_block, s_feature_ro_compat) - 100usize];
    ["Offset of field: ext2_super_block::s_uuid"]
        [::core::mem::offset_of!(ext2_super_block, s_uuid) - 104usize];
    ["Offset of field: ext2_super_block::s_volume_name"]
        [::core::mem::offset_of!(ext2_super_block, s_volume_name) - 120usize];
    ["Offset of field: ext2_super_block::s_last_mounted"]
        [::core::mem::offset_of!(ext2_super_block, s_last_mounted) - 136usize];
    ["Offset of field: ext2_super_block::s_algorithm_usage_bitmap"]
        [::core::mem::offset_of!(ext2_super_block, s_algorithm_usage_bitmap) - 200usize];
    ["Offset of field: ext2_super_block::s_prealloc_blocks"]
        [::core::mem::offset_of!(ext2_super_block, s_prealloc_blocks) - 204usize];
    ["Offset of field: ext2_super_block::s_prealloc_dir_blocks"]
        [::core::mem::offset_of!(ext2_super_block, s_prealloc_dir_blocks) - 205usize];
    ["Offset of field: ext2_super_block::s_reserved_gdt_blocks"]
        [::core::mem::offset_of!(ext2_super_block, s_reserved_gdt_blocks) - 206usize];
    ["Offset of field: ext2_super_block::s_journal_uuid"]
        [::core::mem::offset_of!(ext2_super_block, s_journal_uuid) - 208usize];
    ["Offset of field: ext2_super_block::s_journal_inum"]
        [::core::mem::offset_of!(ext2_super_block, s_journal_inum) - 224usize];
    ["Offset of field: ext2_super_block::s_journal_dev"]
        [::core::mem::offset_of!(ext2_super_block, s_journal_dev) - 228usize];
    ["Offset of field: ext2_super_block::s_last_orphan"]
        [::core::mem::offset_of!(ext2_super_block, s_last_orphan) - 232usize];
    ["Offset of field: ext2_super_block::s_hash_seed"]
        [::core::mem::offset_of!(ext2_super_block, s_hash_seed) - 236usize];
    ["Offset of field: ext2_super_block::s_def_hash_version"]
        [::core::mem::offset_of!(ext2_super_block, s_def_hash_version) - 252usize];
    ["Offset of field: ext2_super_block::s_jnl_backup_type"]
        [::core::mem::offset_of!(ext2_super_block, s_jnl_backup_type) - 253usize];
    ["Offset of field: ext2_super_block::s_desc_size"]
        [::core::mem::offset_of!(ext2_super_block, s_desc_size) - 254usize];
    ["Offset of field: ext2_super_block::s_default_mount_opts"]
        [::core::mem::offset_of!(ext2_super_block, s_default_mount_opts) - 256usize];
    ["Offset of field: ext2_super_block::s_first_meta_bg"]
        [::core::mem::offset_of!(ext2_super_block, s_first_meta_bg) - 260usize];
    ["Offset of field: ext2_super_block::s_mkfs_time"]
        [::core::mem::offset_of!(ext2_super_block, s_mkfs_time) - 264usize];
    ["Offset of field: ext2_super_block::s_jnl_blocks"]
        [::core::mem::offset_of!(ext2_super_block, s_jnl_blocks) - 268usize];
    ["Offset of field: ext2_super_block::s_blocks_count_hi"]
        [::core::mem::offset_of!(ext2_super_block, s_blocks_count_hi) - 336usize];
    ["Offset of field: ext2_super_block::s_r_blocks_count_hi"]
        [::core::mem::offset_of!(ext2_super_block, s_r_blocks_count_hi) - 340usize];
    ["Offset of field: ext2_super_block::s_free_blocks_hi"]
        [::core::mem::offset_of!(ext2_super_block, s_free_blocks_hi) - 344usize];
    ["Offset of field: ext2_super_block::s_min_extra_isize"]
        [::core::mem::offset_of!(ext2_super_block, s_min_extra_isize) - 348usize];
    ["Offset of field: ext2_super_block::s_want_extra_isize"]
        [::core::mem::offset_of!(ext2_super_block, s_want_extra_isize) - 350usize];
    ["Offset of field: ext2_super_block::s_flags"]
        [::core::mem::offset_of!(ext2_super_block, s_flags) - 352usize];
    ["Offset of field: ext2_super_block::s_raid_stride"]
        [::core::mem::offset_of!(ext2_super_block, s_raid_stride) - 356usize];
    ["Offset of field: ext2_super_block::s_mmp_update_interval"]
        [::core::mem::offset_of!(ext2_super_block, s_mmp_update_interval) - 358usize];
    ["Offset of field: ext2_super_block::s_mmp_block"]
        [::core::mem::offset_of!(ext2_super_block, s_mmp_block) - 360usize];
    ["Offset of field: ext2_super_block::s_raid_stripe_width"]
        [::core::mem::offset_of!(ext2_super_block, s_raid_stripe_width) - 368usize];
    ["Offset of field: ext2_super_block::s_log_groups_per_flex"]
        [::core::mem::offset_of!(ext2_super_block, s_log_groups_per_flex) - 372usize];
    ["Offset of field: ext2_super_block::s_checksum_type"]
        [::core::mem::offset_of!(ext2_super_block, s_checksum_type) - 373usize];
    ["Offset of field: ext2_super_block::s_encryption_level"]
        [::core::mem::offset_of!(ext2_super_block, s_encryption_level) - 374usize];
    ["Offset of field: ext2_super_block::s_reserved_pad"]
        [::core::mem::offset_of!(ext2_super_block, s_reserved_pad) - 375usize];
    ["Offset of field: ext2_super_block::s_kbytes_written"]
        [::core::mem::offset_of!(ext2_super_block, s_kbytes_written) - 376usize];
    ["Offset of field: ext2_super_block::s_snapshot_inum"]
        [::core::mem::offset_of!(ext2_super_block, s_snapshot_inum) - 384usize];
    ["Offset of field: ext2_super_block::s_snapshot_id"]
        [::core::mem::offset_of!(ext2_super_block, s_snapshot_id) - 388usize];
    ["Offset of field: ext2_super_block::s_snapshot_r_blocks_count"]
        [::core::mem::offset_of!(ext2_super_block, s_snapshot_r_blocks_count) - 392usize];
    ["Offset of field: ext2_super_block::s_snapshot_list"]
        [::core::mem::offset_of!(ext2_super_block, s_snapshot_list) - 400usize];
    ["Offset of field: ext2_super_block::s_error_count"]
        [::core::mem::offset_of!(ext2_super_block, s_error_count) - 404usize];
    ["Offset of field: ext2_super_block::s_first_error_time"]
        [::core::mem::offset_of!(ext2_super_block, s_first_error_time) - 408usize];
    ["Offset of field: ext2_super_block::s_first_error_ino"]
        [::core::mem::offset_of!(ext2_super_block, s_first_error_ino) - 412usize];
    ["Offset of field: ext2_super_block::s_first_error_block"]
        [::core::mem::offset_of!(ext2_super_block, s_first_error_block) - 416usize];
    ["Offset of field: ext2_super_block::s_first_error_func"]
        [::core::mem::offset_of!(ext2_super_block, s_first_error_func) - 424usize];
    ["Offset of field: ext2_super_block::s_first_error_line"]
        [::core::mem::offset_of!(ext2_super_block, s_first_error_line) - 456usize];
    ["Offset of field: ext2_super_block::s_last_error_time"]
        [::core::mem::offset_of!(ext2_super_block, s_last_error_time) - 460usize];
    ["Offset of field: ext2_super_block::s_last_error_ino"]
        [::core::mem::offset_of!(ext2_super_block, s_last_error_ino) - 464usize];
    ["Offset of field: ext2_super_block::s_last_error_line"]
        [::core::mem::offset_of!(ext2_super_block, s_last_error_line) - 468usize];
    ["Offset of field: ext2_super_block::s_last_error_block"]
        [::core::mem::offset_of!(ext2_super_block, s_last_error_block) - 472usize];
    ["Offset of field: ext2_super_block::s_last_error_func"]
        [::core::mem::offset_of!(ext2_super_block, s_last_error_func) - 480usize];
    ["Offset of field: ext2_super_block::s_mount_opts"]
        [::core::mem::offset_of!(ext2_super_block, s_mount_opts) - 512usize];
    ["Offset of field: ext2_super_block::s_usr_quota_inum"]
        [::core::mem::offset_of!(ext2_super_block, s_usr_quota_inum) - 576usize];
    ["Offset of field: ext2_super_block::s_grp_quota_inum"]
        [::core::mem::offset_of!(ext2_super_block, s_grp_quota_inum) - 580usize];
    ["Offset of field: ext2_super_block::s_overhead_clusters"]
        [::core::mem::offset_of!(ext2_super_block, s_overhead_clusters) - 584usize];
    ["Offset of field: ext2_super_block::s_backup_bgs"]
        [::core::mem::offset_of!(ext2_super_block, s_backup_bgs) - 588usize];
    ["Offset of field: ext2_super_block::s_encrypt_algos"]
        [::core::mem::offset_of!(ext2_super_block, s_encrypt_algos) - 596usize];
    ["Offset of field: ext2_super_block::s_encrypt_pw_salt"]
        [::core::mem::offset_of!(ext2_super_block, s_encrypt_pw_salt) - 600usize];
    ["Offset of field: ext2_super_block::s_lpf_ino"]
        [::core::mem::offset_of!(ext2_super_block, s_lpf_ino) - 616usize];
    ["Offset of field: ext2_super_block::s_prj_quota_inum"]
        [::core::mem::offset_of!(ext2_super_block, s_prj_quota_inum) - 620usize];
    ["Offset of field: ext2_super_block::s_checksum_seed"]
        [::core::mem::offset_of!(ext2_super_block, s_checksum_seed) - 624usize];
    ["Offset of field: ext2_super_block::s_wtime_hi"]
        [::core::mem::offset_of!(ext2_super_block, s_wtime_hi) - 628usize];
    ["Offset of field: ext2_super_block::s_mtime_hi"]
        [::core::mem::offset_of!(ext2_super_block, s_mtime_hi) - 629usize];
    ["Offset of field: ext2_super_block::s_mkfs_time_hi"]
        [::core::mem::offset_of!(ext2_super_block, s_mkfs_time_hi) - 630usize];
    ["Offset of field: ext2_super_block::s_lastcheck_hi"]
        [::core::mem::offset_of!(ext2_super_block, s_lastcheck_hi) - 631usize];
    ["Offset of field: ext2_super_block::s_first_error_time_hi"]
        [::core::mem::offset_of!(ext2_super_block, s_first_error_time_hi) - 632usize];
    ["Offset of field: ext2_super_block::s_last_error_time_hi"]
        [::core::mem::offset_of!(ext2_super_block, s_last_error_time_hi) - 633usize];
    ["Offset of field: ext2_super_block::s_first_error_errcode"]
        [::core::mem::offset_of!(ext2_super_block, s_first_error_errcode) - 634usize];
    ["Offset of field: ext2_super_block::s_last_error_errcode"]
        [::core::mem::offset_of!(ext2_super_block, s_last_error_errcode) - 635usize];
    ["Offset of field: ext2_super_block::s_encoding"]
        [::core::mem::offset_of!(ext2_super_block, s_encoding) - 636usize];
    ["Offset of field: ext2_super_block::s_encoding_flags"]
        [::core::mem::offset_of!(ext2_super_block, s_encoding_flags) - 638usize];
    ["Offset of field: ext2_super_block::s_orphan_file_inum"]
        [::core::mem::offset_of!(ext2_super_block, s_orphan_file_inum) - 640usize];
    ["Offset of field: ext2_super_block::s_reserved"]
        [::core::mem::offset_of!(ext2_super_block, s_reserved) - 644usize];
    ["Offset of field: ext2_super_block::s_checksum"]
        [::core::mem::offset_of!(ext2_super_block, s_checksum) - 1020usize];
};
impl Default for ext2_super_block {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type ext2_ino_t = __u32;
pub type blk_t = __u32;
pub type blk64_t = __u64;
pub type dgrp_t = __u32;
pub type errcode_t = ::core::ffi::c_long;
pub type io_manager = *mut struct_io_manager;
pub type io_channel = *mut struct_io_channel;
pub type io_stats = *mut struct_io_stats;
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct struct_io_channel {
    pub magic: errcode_t,
    pub manager: io_manager,
    pub name: *mut ::core::ffi::c_char,
    pub block_size: ::core::ffi::c_int,
    pub read_error: ::core::option::Option<
        unsafe extern "C" fn(
            channel: io_channel,
            block: ::core::ffi::c_ulong,
            count: ::core::ffi::c_int,
            data: *mut ::core::ffi::c_void,
            size: usize,
            actual_bytes_read: ::core::ffi::c_int,
            error: errcode_t,
        ) -> errcode_t,
    >,
    pub write_error: ::core::option::Option<
        unsafe extern "C" fn(
            channel: io_channel,
            block: ::core::ffi::c_ulong,
            count: ::core::ffi::c_int,
            data: *const ::core::ffi::c_void,
            size: usize,
            actual_bytes_written: ::core::ffi::c_int,
            error: errcode_t,
        ) -> errcode_t,
    >,
    pub refcount: ::core::ffi::c_int,
    pub flags: ::core::ffi::c_uint,
    pub reserved: [::core::ffi::c_long; 14usize],
    pub private_data: *mut ::core::ffi::c_void,
    pub app_data: *mut ::core::ffi::c_void,
    pub align: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of struct_io_channel"][::core::mem::size_of::<struct_io_channel>() - 192usize];
    ["Alignment of struct_io_channel"][::core::mem::align_of::<struct_io_channel>() - 8usize];
    ["Offset of field: struct_io_channel::magic"]
        [::core::mem::offset_of!(struct_io_channel, magic) - 0usize];
    ["Offset of field: struct_io_channel::manager"]
        [::core::mem::offset_of!(struct_io_channel, manager) - 8usize];
    ["Offset of field: struct_io_channel::name"]
        [::core::mem::offset_of!(struct_io_channel, name) - 16usize];
    ["Offset of field: struct_io_channel::block_size"]
        [::core::mem::offset_of!(struct_io_channel, block_size) - 24usize];
    ["Offset of field: struct_io_channel::read_error"]
        [::core::mem::offset_of!(struct_io_channel, read_error) - 32usize];
    ["Offset of field: struct_io_channel::write_error"]
        [::core::mem::offset_of!(struct_io_channel, write_error) - 40usize];
    ["Offset of field: struct_io_channel::refcount"]
        [::core::mem::offset_of!(struct_io_channel, refcount) - 48usize];
    ["Offset of field: struct_io_channel::flags"]
        [::core::mem::offset_of!(struct_io_channel, flags) - 52usize];
    ["Offset of field: struct_io_channel::reserved"]
        [::core::mem::offset_of!(struct_io_channel, reserved) - 56usize];
    ["Offset of field: struct_io_channel::private_data"]
        [::core::mem::offset_of!(struct_io_channel, private_data) - 168usize];
    ["Offset of field: struct_io_channel::app_data"]
        [::core::mem::offset_of!(struct_io_channel, app_data) - 176usize];
    ["Offset of field: struct_io_channel::align"]
        [::core::mem::offset_of!(struct_io_channel, align) - 184usize];
};
impl Default for struct_io_channel {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct struct_io_stats {
    pub num_fields: ::core::ffi::c_int,
    pub reserved: ::core::ffi::c_int,
    pub bytes_read: ::core::ffi::c_ulonglong,
    pub bytes_written: ::core::ffi::c_ulonglong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of struct_io_stats"][::core::mem::size_of::<struct_io_stats>() - 24usize];
    ["Alignment of struct_io_stats"][::core::mem::align_of::<struct_io_stats>() - 8usize];
    ["Offset of field: struct_io_stats::num_fields"]
        [::core::mem::offset_of!(struct_io_stats, num_fields) - 0usize];
    ["Offset of field: struct_io_stats::reserved"]
        [::core::mem::offset_of!(struct_io_stats, reserved) - 4usize];
    ["Offset of field: struct_io_stats::bytes_read"]
        [::core::mem::offset_of!(struct_io_stats, bytes_read) - 8usize];
    ["Offset of field: struct_io_stats::bytes_written"]
        [::core::mem::offset_of!(struct_io_stats, bytes_written) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct struct_io_manager {
    pub magic: errcode_t,
    pub name: *const ::core::ffi::c_char,
    pub open: ::core::option::Option<
        unsafe extern "C" fn(
            name: *const ::core::ffi::c_char,
            flags: ::core::ffi::c_int,
            channel: *mut io_channel,
        ) -> errcode_t,
    >,
    pub close: ::core::option::Option<unsafe extern "C" fn(channel: io_channel) -> errcode_t>,
    pub set_blksize: ::core::option::Option<
        unsafe extern "C" fn(channel: io_channel, blksize: ::core::ffi::c_int) -> errcode_t,
    >,
    pub read_blk: ::core::option::Option<
        unsafe extern "C" fn(
            channel: io_channel,
            block: ::core::ffi::c_ulong,
            count: ::core::ffi::c_int,
            data: *mut ::core::ffi::c_void,
        ) -> errcode_t,
    >,
    pub write_blk: ::core::option::Option<
        unsafe extern "C" fn(
            channel: io_channel,
            block: ::core::ffi::c_ulong,
            count: ::core::ffi::c_int,
            data: *const ::core::ffi::c_void,
        ) -> errcode_t,
    >,
    pub flush: ::core::option::Option<unsafe extern "C" fn(channel: io_channel) -> errcode_t>,
    pub write_byte: ::core::option::Option<
        unsafe extern "C" fn(
            channel: io_channel,
            offset: ::core::ffi::c_ulong,
            count: ::core::ffi::c_int,
            data: *const ::core::ffi::c_void,
        ) -> errcode_t,
    >,
    pub set_option: ::core::option::Option<
        unsafe extern "C" fn(
            channel: io_channel,
            option: *const ::core::ffi::c_char,
            arg: *const ::core::ffi::c_char,
        ) -> errcode_t,
    >,
    pub get_stats: ::core::option::Option<
        unsafe extern "C" fn(channel: io_channel, io_stats: *mut io_stats) -> errcode_t,
    >,
    pub read_blk64: ::core::option::Option<
        unsafe extern "C" fn(
            channel: io_channel,
            block: ::core::ffi::c_ulonglong,
            count: ::core::ffi::c_int,
            data: *mut ::core::ffi::c_void,
        ) -> errcode_t,
    >,
    pub write_blk64: ::core::option::Option<
        unsafe extern "C" fn(
            channel: io_channel,
            block: ::core::ffi::c_ulonglong,
            count: ::core::ffi::c_int,
            data: *const ::core::ffi::c_void,
        ) -> errcode_t,
    >,
    pub discard: ::core::option::Option<
        unsafe extern "C" fn(
            channel: io_channel,
            block: ::core::ffi::c_ulonglong,
            count: ::core::ffi::c_ulonglong,
        ) -> errcode_t,
    >,
    pub cache_readahead: ::core::option::Option<
        unsafe extern "C" fn(
            channel: io_channel,
            block: ::core::ffi::c_ulonglong,
            count: ::core::ffi::c_ulonglong,
        ) -> errcode_t,
    >,
    pub zeroout: ::core::option::Option<
        unsafe extern "C" fn(
            channel: io_channel,
            block: ::core::ffi::c_ulonglong,
            count: ::core::ffi::c_ulonglong,
        ) -> errcode_t,
    >,
    pub reserved: [::core::ffi::c_long; 14usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of struct_io_manager"][::core::mem::size_of::<struct_io_manager>() - 240usize];
    ["Alignment of struct_io_manager"][::core::mem::align_of::<struct_io_manager>() - 8usize];
    ["Offset of field: struct_io_manager::magic"]
        [::core::mem::offset_of!(struct_io_manager, magic) - 0usize];
    ["Offset of field: struct_io_manager::name"]
        [::core::mem::offset_of!(struct_io_manager, name) - 8usize];
    ["Offset of field: struct_io_manager::open"]
        [::core::mem::offset_of!(struct_io_manager, open) - 16usize];
    ["Offset of field: struct_io_manager::close"]
        [::core::mem::offset_of!(struct_io_manager, close) - 24usize];
    ["Offset of field: struct_io_manager::set_blksize"]
        [::core::mem::offset_of!(struct_io_manager, set_blksize) - 32usize];
    ["Offset of field: struct_io_manager::read_blk"]
        [::core::mem::offset_of!(struct_io_manager, read_blk) - 40usize];
    ["Offset of field: struct_io_manager::write_blk"]
        [::core::mem::offset_of!(struct_io_manager, write_blk) - 48usize];
    ["Offset of field: struct_io_manager::flush"]
        [::core::mem::offset_of!(struct_io_manager, flush) - 56usize];
    ["Offset of field: struct_io_manager::write_byte"]
        [::core::mem::offset_of!(struct_io_manager, write_byte) - 64usize];
    ["Offset of field: struct_io_manager::set_option"]
        [::core::mem::offset_of!(struct_io_manager, set_option) - 72usize];
    ["Offset of field: struct_io_manager::get_stats"]
        [::core::mem::offset_of!(struct_io_manager, get_stats) - 80usize];
    ["Offset of field: struct_io_manager::read_blk64"]
        [::core::mem::offset_of!(struct_io_manager, read_blk64) - 88usize];
    ["Offset of field: struct_io_manager::write_blk64"]
        [::core::mem::offset_of!(struct_io_manager, write_blk64) - 96usize];
    ["Offset of field: struct_io_manager::discard"]
        [::core::mem::offset_of!(struct_io_manager, discard) - 104usize];
    ["Offset of field: struct_io_manager::cache_readahead"]
        [::core::mem::offset_of!(struct_io_manager, cache_readahead) - 112usize];
    ["Offset of field: struct_io_manager::zeroout"]
        [::core::mem::offset_of!(struct_io_manager, zeroout) - 120usize];
    ["Offset of field: struct_io_manager::reserved"]
        [::core::mem::offset_of!(struct_io_manager, reserved) - 128usize];
};
impl Default for struct_io_manager {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub static mut unix_io_manager: io_manager;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ext2fs_hashmap {
    _unused: [u8; 0],
}
pub type ext2_filsys = *mut struct_ext2_filsys;
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct ext2fs_struct_generic_bitmap_base {
    pub magic: errcode_t,
    pub fs: ext2_filsys,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ext2fs_struct_generic_bitmap_base"]
        [::core::mem::size_of::<ext2fs_struct_generic_bitmap_base>() - 16usize];
    ["Alignment of ext2fs_struct_generic_bitmap_base"]
        [::core::mem::align_of::<ext2fs_struct_generic_bitmap_base>() - 8usize];
    ["Offset of field: ext2fs_struct_generic_bitmap_base::magic"]
        [::core::mem::offset_of!(ext2fs_struct_generic_bitmap_base, magic) - 0usize];
    ["Offset of field: ext2fs_struct_generic_bitmap_base::fs"]
        [::core::mem::offset_of!(ext2fs_struct_generic_bitmap_base, fs) - 8usize];
};
impl Default for ext2fs_struct_generic_bitmap_base {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type ext2fs_inode_bitmap = *mut ext2fs_struct_generic_bitmap_base;
pub type ext2fs_block_bitmap = *mut ext2fs_struct_generic_bitmap_base;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ext2_struct_u32_list {
    _unused: [u8; 0],
}
pub type ext2_badblocks_list = *mut ext2_struct_u32_list;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ext2_struct_dblist {
    _unused: [u8; 0],
}
pub type ext2_dblist = *mut ext2_struct_dblist;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct opaque_ext2_group_desc {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct struct_ext2_filsys {
    pub magic: errcode_t,
    pub io: io_channel,
    pub flags: ::core::ffi::c_int,
    pub device_name: *mut ::core::ffi::c_char,
    pub super_: *mut ext2_super_block,
    pub blocksize: ::core::ffi::c_uint,
    pub fragsize: ::core::ffi::c_int,
    pub group_desc_count: dgrp_t,
    pub desc_blocks: ::core::ffi::c_ulong,
    pub group_desc: *mut opaque_ext2_group_desc,
    pub inode_blocks_per_group: ::core::ffi::c_uint,
    pub inode_map: ext2fs_inode_bitmap,
    pub block_map: ext2fs_block_bitmap,
    pub get_blocks: ::core::option::Option<
        unsafe extern "C" fn(fs: ext2_filsys, ino: ext2_ino_t, blocks: *mut blk_t) -> errcode_t,
    >,
    pub check_directory:
        ::core::option::Option<unsafe extern "C" fn(fs: ext2_filsys, ino: ext2_ino_t) -> errcode_t>,
    pub write_bitmaps: ::core::option::Option<unsafe extern "C" fn(fs: ext2_filsys) -> errcode_t>,
    pub read_inode: ::core::option::Option<
        unsafe extern "C" fn(fs: ext2_filsys, ino: ext2_ino_t, inode: *mut ext2_inode) -> errcode_t,
    >,
    pub write_inode: ::core::option::Option<
        unsafe extern "C" fn(fs: ext2_filsys, ino: ext2_ino_t, inode: *mut ext2_inode) -> errcode_t,
    >,
    pub badblocks: ext2_badblocks_list,
    pub dblist: ext2_dblist,
    pub stride: __u32,
    pub orig_super: *mut ext2_super_block,
    pub image_header: *mut ext2_image_hdr,
    pub umask: __u32,
    pub now: time_t,
    pub cluster_ratio_bits: ::core::ffi::c_int,
    pub default_bitmap_type: __u16,
    pub pad: __u16,
    pub flags2: __u32,
    pub reserved: [__u32; 4usize],
    pub priv_data: *mut ::core::ffi::c_void,
    pub icache: *mut ext2_inode_cache,
    pub image_io: io_channel,
    pub get_alloc_block: ::core::option::Option<
        unsafe extern "C" fn(fs: ext2_filsys, goal: blk64_t, ret: *mut blk64_t) -> errcode_t,
    >,
    pub get_alloc_block2: ::core::option::Option<
        unsafe extern "C" fn(
            fs: ext2_filsys,
            goal: blk64_t,
            ret: *mut blk64_t,
            ctx: *mut blk_alloc_ctx,
        ) -> errcode_t,
    >,
    pub block_alloc_stats: ::core::option::Option<
        unsafe extern "C" fn(fs: ext2_filsys, blk: blk64_t, inuse: ::core::ffi::c_int),
    >,
    pub mmp_buf: *mut ::core::ffi::c_void,
    pub mmp_cmp: *mut ::core::ffi::c_void,
    pub mmp_fd: ::core::ffi::c_int,
    pub mmp_last_written: ::core::ffi::c_long,
    pub progress_ops: *mut ext2fs_progress_ops,
    pub csum_seed: __u32,
    pub journal_io: io_channel,
    pub journal_name: *mut ::core::ffi::c_char,
    pub new_range: ::core::option::Option<
        unsafe extern "C" fn(
            fs: ext2_filsys,
            flags: ::core::ffi::c_int,
            goal: blk64_t,
            len: blk64_t,
            pblk: *mut blk64_t,
            plen: *mut blk64_t,
        ) -> errcode_t,
    >,
    pub block_alloc_stats_range: ::core::option::Option<
        unsafe extern "C" fn(fs: ext2_filsys, blk: blk64_t, num: blk_t, inuse: ::core::ffi::c_int),
    >,
    pub block_sha_map: *mut ext2fs_hashmap,
    pub encoding: *mut ext2fs_nls_table,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of struct_ext2_filsys"][::core::mem::size_of::<struct_ext2_filsys>() - 368usize];
    ["Alignment of struct_ext2_filsys"][::core::mem::align_of::<struct_ext2_filsys>() - 8usize];
    ["Offset of field: struct_ext2_filsys::magic"]
        [::core::mem::offset_of!(struct_ext2_filsys, magic) - 0usize];
    ["Offset of field: struct_ext2_filsys::io"]
        [::core::mem::offset_of!(struct_ext2_filsys, io) - 8usize];
    ["Offset of field: struct_ext2_filsys::flags"]
        [::core::mem::offset_of!(struct_ext2_filsys, flags) - 16usize];
    ["Offset of field: struct_ext2_filsys::device_name"]
        [::core::mem::offset_of!(struct_ext2_filsys, device_name) - 24usize];
    ["Offset of field: struct_ext2_filsys::super_"]
        [::core::mem::offset_of!(struct_ext2_filsys, super_) - 32usize];
    ["Offset of field: struct_ext2_filsys::blocksize"]
        [::core::mem::offset_of!(struct_ext2_filsys, blocksize) - 40usize];
    ["Offset of field: struct_ext2_filsys::fragsize"]
        [::core::mem::offset_of!(struct_ext2_filsys, fragsize) - 44usize];
    ["Offset of field: struct_ext2_filsys::group_desc_count"]
        [::core::mem::offset_of!(struct_ext2_filsys, group_desc_count) - 48usize];
    ["Offset of field: struct_ext2_filsys::desc_blocks"]
        [::core::mem::offset_of!(struct_ext2_filsys, desc_blocks) - 56usize];
    ["Offset of field: struct_ext2_filsys::group_desc"]
        [::core::mem::offset_of!(struct_ext2_filsys, group_desc) - 64usize];
    ["Offset of field: struct_ext2_filsys::inode_blocks_per_group"]
        [::core::mem::offset_of!(struct_ext2_filsys, inode_blocks_per_group) - 72usize];
    ["Offset of field: struct_ext2_filsys::inode_map"]
        [::core::mem::offset_of!(struct_ext2_filsys, inode_map) - 80usize];
    ["Offset of field: struct_ext2_filsys::block_map"]
        [::core::mem::offset_of!(struct_ext2_filsys, block_map) - 88usize];
    ["Offset of field: struct_ext2_filsys::get_blocks"]
        [::core::mem::offset_of!(struct_ext2_filsys, get_blocks) - 96usize];
    ["Offset of field: struct_ext2_filsys::check_directory"]
        [::core::mem::offset_of!(struct_ext2_filsys, check_directory) - 104usize];
    ["Offset of field: struct_ext2_filsys::write_bitmaps"]
        [::core::mem::offset_of!(struct_ext2_filsys, write_bitmaps) - 112usize];
    ["Offset of field: struct_ext2_filsys::read_inode"]
        [::core::mem::offset_of!(struct_ext2_filsys, read_inode) - 120usize];
    ["Offset of field: struct_ext2_filsys::write_inode"]
        [::core::mem::offset_of!(struct_ext2_filsys, write_inode) - 128usize];
    ["Offset of field: struct_ext2_filsys::badblocks"]
        [::core::mem::offset_of!(struct_ext2_filsys, badblocks) - 136usize];
    ["Offset of field: struct_ext2_filsys::dblist"]
        [::core::mem::offset_of!(struct_ext2_filsys, dblist) - 144usize];
    ["Offset of field: struct_ext2_filsys::stride"]
        [::core::mem::offset_of!(struct_ext2_filsys, stride) - 152usize];
    ["Offset of field: struct_ext2_filsys::orig_super"]
        [::core::mem::offset_of!(struct_ext2_filsys, orig_super) - 160usize];
    ["Offset of field: struct_ext2_filsys::image_header"]
        [::core::mem::offset_of!(struct_ext2_filsys, image_header) - 168usize];
    ["Offset of field: struct_ext2_filsys::umask"]
        [::core::mem::offset_of!(struct_ext2_filsys, umask) - 176usize];
    ["Offset of field: struct_ext2_filsys::now"]
        [::core::mem::offset_of!(struct_ext2_filsys, now) - 184usize];
    ["Offset of field: struct_ext2_filsys::cluster_ratio_bits"]
        [::core::mem::offset_of!(struct_ext2_filsys, cluster_ratio_bits) - 192usize];
    ["Offset of field: struct_ext2_filsys::default_bitmap_type"]
        [::core::mem::offset_of!(struct_ext2_filsys, default_bitmap_type) - 196usize];
    ["Offset of field: struct_ext2_filsys::pad"]
        [::core::mem::offset_of!(struct_ext2_filsys, pad) - 198usize];
    ["Offset of field: struct_ext2_filsys::flags2"]
        [::core::mem::offset_of!(struct_ext2_filsys, flags2) - 200usize];
    ["Offset of field: struct_ext2_filsys::reserved"]
        [::core::mem::offset_of!(struct_ext2_filsys, reserved) - 204usize];
    ["Offset of field: struct_ext2_filsys::priv_data"]
        [::core::mem::offset_of!(struct_ext2_filsys, priv_data) - 224usize];
    ["Offset of field: struct_ext2_filsys::icache"]
        [::core::mem::offset_of!(struct_ext2_filsys, icache) - 232usize];
    ["Offset of field: struct_ext2_filsys::image_io"]
        [::core::mem::offset_of!(struct_ext2_filsys, image_io) - 240usize];
    ["Offset of field: struct_ext2_filsys::get_alloc_block"]
        [::core::mem::offset_of!(struct_ext2_filsys, get_alloc_block) - 248usize];
    ["Offset of field: struct_ext2_filsys::get_alloc_block2"]
        [::core::mem::offset_of!(struct_ext2_filsys, get_alloc_block2) - 256usize];
    ["Offset of field: struct_ext2_filsys::block_alloc_stats"]
        [::core::mem::offset_of!(struct_ext2_filsys, block_alloc_stats) - 264usize];
    ["Offset of field: struct_ext2_filsys::mmp_buf"]
        [::core::mem::offset_of!(struct_ext2_filsys, mmp_buf) - 272usize];
    ["Offset of field: struct_ext2_filsys::mmp_cmp"]
        [::core::mem::offset_of!(struct_ext2_filsys, mmp_cmp) - 280usize];
    ["Offset of field: struct_ext2_filsys::mmp_fd"]
        [::core::mem::offset_of!(struct_ext2_filsys, mmp_fd) - 288usize];
    ["Offset of field: struct_ext2_filsys::mmp_last_written"]
        [::core::mem::offset_of!(struct_ext2_filsys, mmp_last_written) - 296usize];
    ["Offset of field: struct_ext2_filsys::progress_ops"]
        [::core::mem::offset_of!(struct_ext2_filsys, progress_ops) - 304usize];
    ["Offset of field: struct_ext2_filsys::csum_seed"]
        [::core::mem::offset_of!(struct_ext2_filsys, csum_seed) - 312usize];
    ["Offset of field: struct_ext2_filsys::journal_io"]
        [::core::mem::offset_of!(struct_ext2_filsys, journal_io) - 320usize];
    ["Offset of field: struct_ext2_filsys::journal_name"]
        [::core::mem::offset_of!(struct_ext2_filsys, journal_name) - 328usize];
    ["Offset of field: struct_ext2_filsys::new_range"]
        [::core::mem::offset_of!(struct_ext2_filsys, new_range) - 336usize];
    ["Offset of field: struct_ext2_filsys::block_alloc_stats_range"]
        [::core::mem::offset_of!(struct_ext2_filsys, block_alloc_stats_range) - 344usize];
    ["Offset of field: struct_ext2_filsys::block_sha_map"]
        [::core::mem::offset_of!(struct_ext2_filsys, block_sha_map) - 352usize];
    ["Offset of field: struct_ext2_filsys::encoding"]
        [::core::mem::offset_of!(struct_ext2_filsys, encoding) - 360usize];
};
impl Default for struct_ext2_filsys {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct blk_alloc_ctx {
    pub ino: ext2_ino_t,
    pub inode: *mut ext2_inode,
    pub lblk: blk64_t,
    pub flags: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of blk_alloc_ctx"][::core::mem::size_of::<blk_alloc_ctx>() - 32usize];
    ["Alignment of blk_alloc_ctx"][::core::mem::align_of::<blk_alloc_ctx>() - 8usize];
    ["Offset of field: blk_alloc_ctx::ino"][::core::mem::offset_of!(blk_alloc_ctx, ino) - 0usize];
    ["Offset of field: blk_alloc_ctx::inode"]
        [::core::mem::offset_of!(blk_alloc_ctx, inode) - 8usize];
    ["Offset of field: blk_alloc_ctx::lblk"]
        [::core::mem::offset_of!(blk_alloc_ctx, lblk) - 16usize];
    ["Offset of field: blk_alloc_ctx::flags"]
        [::core::mem::offset_of!(blk_alloc_ctx, flags) - 24usize];
};
impl Default for blk_alloc_ctx {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn ext2fs_new_inode(
        fs: ext2_filsys,
        dir: ext2_ino_t,
        mode: ::core::ffi::c_int,
        map: ext2fs_inode_bitmap,
        ret: *mut ext2_ino_t,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn ext2fs_new_block2(
        fs: ext2_filsys,
        goal: blk64_t,
        map: ext2fs_block_bitmap,
        ret: *mut blk64_t,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn ext2fs_inode_alloc_stats2(
        fs: ext2_filsys,
        ino: ext2_ino_t,
        inuse: ::core::ffi::c_int,
        isdir: ::core::ffi::c_int,
    );
}
unsafe extern "C" {
    pub fn ext2fs_block_alloc_stats2(fs: ext2_filsys, blk: blk64_t, inuse: ::core::ffi::c_int);
}
unsafe extern "C" {
    pub fn ext2fs_allocate_tables(fs: ext2_filsys) -> errcode_t;
}
unsafe extern "C" {
    pub fn ext2fs_close(fs: ext2_filsys) -> errcode_t;
}
unsafe extern "C" {
    pub fn ext2fs_flush(fs: ext2_filsys) -> errcode_t;
}
unsafe extern "C" {
    pub fn ext2fs_initialize(
        name: *const ::core::ffi::c_char,
        flags: ::core::ffi::c_int,
        param: *mut ext2_super_block,
        manager: io_manager,
        ret_fs: *mut ext2_filsys,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn ext2fs_read_inode_full(
        fs: ext2_filsys,
        ino: ext2_ino_t,
        inode: *mut ext2_inode,
        bufsize: ::core::ffi::c_int,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn ext2fs_read_inode(fs: ext2_filsys, ino: ext2_ino_t, inode: *mut ext2_inode)
    -> errcode_t;
}
unsafe extern "C" {
    pub fn ext2fs_write_inode_full(
        fs: ext2_filsys,
        ino: ext2_ino_t,
        inode: *mut ext2_inode,
        bufsize: ::core::ffi::c_int,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn ext2fs_write_inode(
        fs: ext2_filsys,
        ino: ext2_ino_t,
        inode: *mut ext2_inode,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn ext2fs_write_new_inode(
        fs: ext2_filsys,
        ino: ext2_ino_t,
        inode: *mut ext2_inode,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn ext2fs_mkdir(
        fs: ext2_filsys,
        parent: ext2_ino_t,
        inum: ext2_ino_t,
        name: *const ::core::ffi::c_char,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn ext2fs_add_journal_inode(
        fs: ext2_filsys,
        num_blocks: blk_t,
        flags: ::core::ffi::c_int,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn ext2fs_open(
        name: *const ::core::ffi::c_char,
        flags: ::core::ffi::c_int,
        superblock: ::core::ffi::c_int,
        block_size: ::core::ffi::c_uint,
        manager: io_manager,
        ret_fs: *mut ext2_filsys,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn ext2fs_link(
        fs: ext2_filsys,
        dir: ext2_ino_t,
        name: *const ::core::ffi::c_char,
        ino: ext2_ino_t,
        flags: ::core::ffi::c_int,
    ) -> errcode_t;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct stat {
    pub st_dev: __dev_t,
    pub st_ino: __ino_t,
    pub st_nlink: __nlink_t,
    pub st_mode: __mode_t,
    pub st_uid: __uid_t,
    pub st_gid: __gid_t,
    pub __pad0: ::core::ffi::c_int,
    pub st_rdev: __dev_t,
    pub st_size: __off_t,
    pub st_blksize: __blksize_t,
    pub st_blocks: __blkcnt_t,
    pub st_atim: timespec,
    pub st_mtim: timespec,
    pub st_ctim: timespec,
    pub __glibc_reserved: [__syscall_slong_t; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of stat"][::core::mem::size_of::<stat>() - 144usize];
    ["Alignment of stat"][::core::mem::align_of::<stat>() - 8usize];
    ["Offset of field: stat::st_dev"][::core::mem::offset_of!(stat, st_dev) - 0usize];
    ["Offset of field: stat::st_ino"][::core::mem::offset_of!(stat, st_ino) - 8usize];
    ["Offset of field: stat::st_nlink"][::core::mem::offset_of!(stat, st_nlink) - 16usize];
    ["Offset of field: stat::st_mode"][::core::mem::offset_of!(stat, st_mode) - 24usize];
    ["Offset of field: stat::st_uid"][::core::mem::offset_of!(stat, st_uid) - 28usize];
    ["Offset of field: stat::st_gid"][::core::mem::offset_of!(stat, st_gid) - 32usize];
    ["Offset of field: stat::__pad0"][::core::mem::offset_of!(stat, __pad0) - 36usize];
    ["Offset of field: stat::st_rdev"][::core::mem::offset_of!(stat, st_rdev) - 40usize];
    ["Offset of field: stat::st_size"][::core::mem::offset_of!(stat, st_size) - 48usize];
    ["Offset of field: stat::st_blksize"][::core::mem::offset_of!(stat, st_blksize) - 56usize];
    ["Offset of field: stat::st_blocks"][::core::mem::offset_of!(stat, st_blocks) - 64usize];
    ["Offset of field: stat::st_atim"][::core::mem::offset_of!(stat, st_atim) - 72usize];
    ["Offset of field: stat::st_mtim"][::core::mem::offset_of!(stat, st_mtim) - 88usize];
    ["Offset of field: stat::st_ctim"][::core::mem::offset_of!(stat, st_ctim) - 104usize];
    ["Offset of field: stat::__glibc_reserved"]
        [::core::mem::offset_of!(stat, __glibc_reserved) - 120usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct hdlink_s {
    pub src_dev: dev_t,
    pub src_ino: ino_t,
    pub dst_ino: ext2_ino_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of hdlink_s"][::core::mem::size_of::<hdlink_s>() - 24usize];
    ["Alignment of hdlink_s"][::core::mem::align_of::<hdlink_s>() - 8usize];
    ["Offset of field: hdlink_s::src_dev"][::core::mem::offset_of!(hdlink_s, src_dev) - 0usize];
    ["Offset of field: hdlink_s::src_ino"][::core::mem::offset_of!(hdlink_s, src_ino) - 8usize];
    ["Offset of field: hdlink_s::dst_ino"][::core::mem::offset_of!(hdlink_s, dst_ino) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct hdlinks_s {
    pub count: ::core::ffi::c_int,
    pub size: ::core::ffi::c_int,
    pub hdl: *mut hdlink_s,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of hdlinks_s"][::core::mem::size_of::<hdlinks_s>() - 16usize];
    ["Alignment of hdlinks_s"][::core::mem::align_of::<hdlinks_s>() - 8usize];
    ["Offset of field: hdlinks_s::count"][::core::mem::offset_of!(hdlinks_s, count) - 0usize];
    ["Offset of field: hdlinks_s::size"][::core::mem::offset_of!(hdlinks_s, size) - 4usize];
    ["Offset of field: hdlinks_s::hdl"][::core::mem::offset_of!(hdlinks_s, hdl) - 8usize];
};
impl Default for hdlinks_s {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct fs_ops_callbacks {
    pub create_new_inode: ::core::option::Option<
        unsafe extern "C" fn(
            fs: ext2_filsys,
            target_path: *const ::core::ffi::c_char,
            name: *const ::core::ffi::c_char,
            parent_ino: ext2_ino_t,
            root: ext2_ino_t,
            mode: mode_t,
        ) -> errcode_t,
    >,
    pub end_create_new_inode: ::core::option::Option<
        unsafe extern "C" fn(
            fs: ext2_filsys,
            target_path: *const ::core::ffi::c_char,
            name: *const ::core::ffi::c_char,
            parent_ino: ext2_ino_t,
            root: ext2_ino_t,
            mode: mode_t,
        ) -> errcode_t,
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of fs_ops_callbacks"][::core::mem::size_of::<fs_ops_callbacks>() - 16usize];
    ["Alignment of fs_ops_callbacks"][::core::mem::align_of::<fs_ops_callbacks>() - 8usize];
    ["Offset of field: fs_ops_callbacks::create_new_inode"]
        [::core::mem::offset_of!(fs_ops_callbacks, create_new_inode) - 0usize];
    ["Offset of field: fs_ops_callbacks::end_create_new_inode"]
        [::core::mem::offset_of!(fs_ops_callbacks, end_create_new_inode) - 8usize];
};
unsafe extern "C" {
    pub fn populate_fs(
        fs: ext2_filsys,
        parent_ino: ext2_ino_t,
        source_dir: *const ::core::ffi::c_char,
        root: ext2_ino_t,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn populate_fs2(
        fs: ext2_filsys,
        parent_ino: ext2_ino_t,
        source_dir: *const ::core::ffi::c_char,
        root: ext2_ino_t,
        fs_callbacks: *mut fs_ops_callbacks,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn do_symlink_internal(
        fs: ext2_filsys,
        cwd: ext2_ino_t,
        name: *const ::core::ffi::c_char,
        target: *mut ::core::ffi::c_char,
        root: ext2_ino_t,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn do_mkdir_internal(
        fs: ext2_filsys,
        cwd: ext2_ino_t,
        name: *const ::core::ffi::c_char,
        root: ext2_ino_t,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn do_write_internal(
        fs: ext2_filsys,
        cwd: ext2_ino_t,
        src: *const ::core::ffi::c_char,
        dest: *const ::core::ffi::c_char,
        root: ext2_ino_t,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn add_link(
        fs: ext2_filsys,
        parent_ino: ext2_ino_t,
        ino: ext2_ino_t,
        name: *const ::core::ffi::c_char,
    ) -> errcode_t;
}
unsafe extern "C" {
    pub fn set_inode_extra(fs: ext2_filsys, ino: ext2_ino_t, st: *const stat) -> errcode_t;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct ext2_image_hdr {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct ext2_inode_cache {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct ext2fs_progress_ops {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct ext2fs_nls_table {
    pub _address: u8,
}
