//! Ext4 filesystem image creation via [`libext2fs`] — static FFI bindings and safe Rust API.
//!
//! This crate provides:
//!
//! - **[`sys`]** — Raw FFI bindings auto-generated by [`bindgen`](https://docs.rs/bindgen)
//!   from the e2fsprogs headers. Statically linked at build time.
//!
//! - **[`Ext4Builder`]** — Safe, high-level API for creating ext4 images from directories
//!   and injecting files into existing images.
//!
//! # Build
//!
//! The build script (`build.rs`) automatically:
//! 1. Downloads pre-built static libraries from [GitHub Releases](https://github.com/qntx/bux/releases)
//!    (or uses `BUX_E2FS_DIR` for local development).
//! 2. Statically links `libext2fs`, `libcom_err`, `libe2p`, `libuuid`, and `libcreate_inode`.
//!
//! [`libext2fs`]: https://e2fsprogs.sourceforge.net/

#![cfg_attr(docsrs, feature(doc_cfg))]

pub mod sys;

mod error;
mod ext4;

pub use error::{Error, Result};
pub use ext4::{Ext4Builder, estimate_image_size};
