//! Ext4 filesystem image creation via [`libext2fs`] — static FFI bindings and safe Rust API.
//!
//! # Architecture
//!
//! - **[`sys`]** — Raw FFI bindings (auto-generated by `bindgen`).
//! - **[`Filesystem`]** — RAII wrapper around `ext2_filsys` with safe operations.
//! - **[`create_from_dir`]** / **[`inject_file`]** — Convenience functions for common tasks.
//!
//! # Quick Start
//!
//! ```no_run
//! use std::path::Path;
//!
//! let size = bux_e2fs::estimate_image_size(Path::new("/tmp/rootfs")).unwrap();
//! bux_e2fs::create_from_dir(
//!     Path::new("/tmp/rootfs"),
//!     Path::new("/tmp/image.raw"),
//!     size,
//! ).unwrap();
//! ```
//!
//! [`libext2fs`]: https://e2fsprogs.sourceforge.net/

#![cfg_attr(docsrs, feature(doc_cfg))]

pub mod sys;

mod error;
mod ext4;

pub use error::{Error, Result};
pub use ext4::{
    BlockSize, CreateOptions, FileType, Filesystem, create_from_dir, estimate_image_size,
    inject_file,
};
