//! Ext4 filesystem image creation via [`libext2fs`] — static FFI bindings and safe Rust API.
//!
//! # Architecture
//!
//! - **[`sys`]** — Raw FFI bindings (auto-generated by `bindgen`).
//! - **[`Filesystem`]** — RAII wrapper around `ext2_filsys` with safe operations.
//! - **[`Ext4Builder`]** — Fluent builder for creating images with custom options.
//! - **[`create_from_dir`]** / **[`inject_file`]** — One-shot convenience functions
//!   for the common case.
//!
//! # Quick Start
//!
//! The shortest path — default options, single call:
//!
//! ```no_run
//! use std::path::Path;
//!
//! let size = bux_e2fs::estimate_image_size(Path::new("/tmp/rootfs")).unwrap();
//! bux_e2fs::create_from_dir(
//!     Path::new("/tmp/rootfs"),
//!     Path::new("/tmp/image.raw"),
//!     size,
//! ).unwrap();
//! ```
//!
//! Custom block size / no journal (ext2) via [`Ext4Builder`]:
//!
//! ```no_run
//! use std::path::Path;
//! use bux_e2fs::{BlockSize, Ext4Builder};
//!
//! Ext4Builder::new()
//!     .block_size(BlockSize::B1024)
//!     .reserved_ratio(5)
//!     .add_journal(false)
//!     .create_from_dir(
//!         Path::new("/tmp/rootfs"),
//!         Path::new("/tmp/image.raw"),
//!         256 * 1024 * 1024,
//!     )
//!     .unwrap();
//! ```
//!
//! [`libext2fs`]: https://e2fsprogs.sourceforge.net/

#![cfg_attr(docsrs, feature(doc_cfg))]
#![allow(
    clippy::allow_attributes_without_reason,
    reason = "bindgen-generated code cannot have reasons"
)]

pub mod sys;

mod error;
mod ext4;

pub use error::{Error, Result};
pub use ext4::{
    BlockSize, CreateOptions, Ext4Builder, FileType, Filesystem, create_from_dir,
    estimate_image_size, inject_file,
};
