//! Guest NIC configuration for gvproxy virtio-net.
//!
//! Static addressing from [`bux_proto::net`].
//!
//! Uses rtnetlink (pure Rust) — no `ip` binary dependency.

use std::fs;
use std::net::Ipv4Addr;

use bux_proto::net::{GATEWAY_IP, GATEWAY_IPV4, GUEST_INTERFACE, GUEST_IP, GUEST_IPV4, PREFIX_LEN};
use futures::stream::TryStreamExt;
use rtnetlink::{LinkUnspec, RouteMessageBuilder, new_connection};

/// Bring up loopback + eth0 with static IP and default route.
///
/// # Errors
///
/// Returns I/O error if eth0 is missing or netlink operations fail.
pub async fn configure_static_eth0() -> std::io::Result<()> {
    let (connection, handle, _) =
        new_connection().map_err(|e| std::io::Error::other(format!("netlink connect: {e}")))?;
    tokio::spawn(connection);

    // lo up
    {
        let mut links = handle.link().get().match_name("lo".to_owned()).execute();
        if let Some(link) = links
            .try_next()
            .await
            .map_err(|e| std::io::Error::other(format!("get lo: {e}")))?
        {
            handle
                .link()
                .set(LinkUnspec::new_with_index(link.header.index).up().build())
                .execute()
                .await
                .map_err(|e| std::io::Error::other(format!("lo up: {e}")))?;
        }
    }

    // eth0
    let mut links = handle
        .link()
        .get()
        .match_name(GUEST_INTERFACE.to_owned())
        .execute();
    let link = links
        .try_next()
        .await
        .map_err(|e| std::io::Error::other(format!("get {GUEST_INTERFACE}: {e}")))?
        .ok_or_else(|| {
            std::io::Error::new(
                std::io::ErrorKind::NotFound,
                format!("{GUEST_INTERFACE} not found — virtio-net missing?"),
            )
        })?;
    let idx = link.header.index;

    handle
        .link()
        .set(LinkUnspec::new_with_index(idx).up().build())
        .execute()
        .await
        .map_err(|e| std::io::Error::other(format!("{GUEST_INTERFACE} up: {e}")))?;

    handle
        .address()
        .add(idx, GUEST_IPV4.into(), PREFIX_LEN)
        .execute()
        .await
        .or_else(|e| {
            // Already assigned is fine on restart paths.
            if e.to_string().contains("File exists") || e.to_string().contains("EEXIST") {
                Ok(())
            } else {
                Err(std::io::Error::other(format!("addr add: {e}")))
            }
        })?;

    let route = RouteMessageBuilder::<Ipv4Addr>::new()
        .gateway(GATEWAY_IPV4)
        .build();
    handle.route().add(route).execute().await.or_else(|e| {
        if e.to_string().contains("File exists") || e.to_string().contains("EEXIST") {
            Ok(())
        } else {
            Err(std::io::Error::other(format!("default route: {e}")))
        }
    })?;

    write_resolv_gateway();
    ensure_hosts_and_hostname();
    Ok(())
}

/// Offline / Disabled network: lo identity only, no eth0 requirement.
pub fn configure_offline() {
    ensure_hosts_and_hostname();
}

/// Point DNS at the gvproxy gateway.
fn write_resolv_gateway() {
    let _ = fs::create_dir_all("/etc");
    let _ = fs::write(
        "/etc/resolv.conf",
        format!("# Generated by bux-guest (gvproxy gateway DNS)\nnameserver {GATEWAY_IP}\n"),
    );
}

/// Ensure `/etc/hosts` and hostname are set for the guest.
fn ensure_hosts_and_hostname() {
    let hosts = std::path::Path::new("/etc/hosts");
    if !hosts.is_file() || fs::read_to_string(hosts).map_or(true, |c| c.is_empty()) {
        let _ = fs::write(
            hosts,
            format!("127.0.0.1 localhost\n::1 localhost\n{GUEST_IP} bux\n"),
        );
    }

    let hostname = std::path::Path::new("/etc/hostname");
    if !hostname.is_file() {
        let _ = fs::write(hostname, "bux\n");
    }
    if let Ok(name) = std::ffi::CString::new("bux") {
        unsafe {
            libc::sethostname(name.as_ptr(), 3);
        }
    }
}
